In [76]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [55]:
df = pd.read_csv(r'D:\batch -3\Machine learning project\Project 23 Stroke Prediction\healthcare-dataset-stroke-data.csv')
df.shape

(5110, 12)

In [56]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [57]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [58]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [59]:
df = df.dropna(how='any')

In [60]:
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [61]:
numeric_columns = df.select_dtypes(include=['number']).columns
non_numeric_columns = df.select_dtypes(exclude=['number']).columns

In [62]:
for col in non_numeric_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [63]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,56669,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [66]:

categorical_columns = ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']
for col in categorical_columns:
    df[col] = df[col].astype(str)  # Ensure columns are treated as strings
    df[col] = df[col].map({'Female': 0, 'Male': 1, 'Yes': 1, 'No': 0, 'private': 1, 'self-employed': 2,'Govt_job':3,'children':4,'Urban':0,'Rural':1,'formerly smoked':0,'never smoked':1,'smokes':2,'Unknown':3})
    
    if df[col].isnull().any():
        df[col] = df[col].fillna(0)

In [67]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,0.0,67.0,0,1,1,0.0,0,228.69,36.6,0,1
2,31112,0.0,80.0,0,1,1,0.0,1,105.92,32.5,1,1
3,60182,0.0,49.0,0,0,1,0.0,0,171.23,34.4,2,1
4,1665,0.0,79.0,1,0,1,0.0,1,174.12,24.0,1,1
5,56669,0.0,81.0,0,0,1,0.0,0,186.21,29.0,0,1

In [68]:
# Features and target
x = df.drop(['stroke', 'id'], axis=1)
y = df['stroke']

In [69]:
print(x)

      gender   age  hypertension  heart_disease  ever_married  work_type  \
0        0.0  67.0             0              1             1        0.0
2        0.0  80.0             0              1             1        0.0
3        0.0  49.0             0              0             1        0.0
4        0.0  79.0             1              0             1        0.0
5        0.0  81.0             0              0             1        0.0
...      ...   ...           ...            ...           ...        ...
5104     0.0  13.0             0              0             0        4.0
5106     0.0  81.0             0              0             1        0.0
5107     0.0  35.0             0              0             1        0.0
5108     0.0  51.0             0              0             1        0.0
5109     0.0  44.0             0              0             1        3.0

      Residence_type  avg_glucose_level   bmi  smoking_status
0                  0             228.69  36.6               0
2                  1             105.92  32.5               1
3                  0             171.23  34.4               2
4                  1             174.12  24.0               1
5                  0             186.21  29.0               0
...              ...                ...   ...             ...
5104               1             103.08  18.6               3
5106               0             125.20  40.0               1
5107               1              82.99  30.6               1
5108               1             166.29  25.6               0
5109               0              85.28  26.2               3

[4909 rows x 10 columns]

In [70]:
print(y)

0       1
2       1
3       1
4       1
5       1
       ..
5104    0
5106    0
5107    0
5108    0
5109    0
Name: stroke, Length: 4909, dtype: int64

In [71]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=2)

In [72]:
model = RandomForestClassifier()
model.fit(xtrain,ytrain)

RandomForestClassifier()

In [73]:
# accuracy on training data
xtrain_prediction = model.predict(xtrain)
training_data_accuracy = accuracy_score(ytrain, xtrain_prediction)

print('Accuracy on training data = ', training_data_accuracy)

Accuracy on training data =  1.0

In [74]:
# accuracy on test data
xtest_prediction = model.predict(xtest)
test_data_accuracy = accuracy_score( xtest_prediction, ytest)

print('Accuracy on test data = ', test_data_accuracy)

Accuracy on test data =  0.9572301425661914

In [77]:
# Evaluate the model
conf_matrix = confusion_matrix(ytest, xtest_prediction)
class_report = classification_report(ytest, xtest_prediction)
print("\nClassification Report:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Classification Report:
 [[940   0]
 [ 42   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98       940
           1       0.00      0.00      0.00        42

    accuracy                           0.96       982
   macro avg       0.48      0.50      0.49       982
weighted avg       0.92      0.96      0.94       982

c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [78]:
input_data = (0,67,0,1,1,0,0,228.69,36.6,0)

# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for one datapoint
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 1):
  print('The person stroked')

else:
  print('The person is not stroked')

[1]
The person stroked

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [79]:
import pickle
     

filename = 'Stroke prediction.sav'
pickle.dump(model, open(filename, 'wb'))
     

# loading the saved model
loaded_model = pickle.load(open('Stroke prediction.sav', 'rb'))

for column in df.columns:
    print(column)

id
gender
age
hypertension
heart_disease
ever_married
work_type
Residence_type
avg_glucose_level
bmi
smoking_status
stroke